version: '3.4'

services:

  basket.api:
    image: eshopai/basket.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile    
      args:
        - configuration
    depends_on:
      - basket.data
      - identity.api
      - rabbitmq

  ai.salesforecasting.mlnet.api:
    image: eshopai/ai.salesforecasting.mlnet.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/AI.SalesForecasting/AI.SalesForecasting.MLNet.API/Dockerfile    
      args:
        - configuration

  ai.productrecommender.azureml.api:
    image: eshopai/ai.productrecommender.azureml.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/AI.ProductRecommender/AI.ProductRecommender.AzureML.API/Dockerfile    
      args:
        - configuration

  ai.productsearchimagebased.tensorflow.api:
    image: eshopai/ai.productsearchimagebased.tensorflow.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/AI.ProductSearchImageBased/AI.ProductSearchImageBased.TensorFlow.API/Dockerfile    
      args:
        - configuration

  ai.productsearchimagebased.azurecognitiveservices.api:
    image: eshopai/ai.productsearchimagebased.azurecognitiveservices.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/AI.ProductSearchImageBased/AI.ProductSearchImageBased.AzureCognitiveServices.API/Dockerfile    
      args:
        - configuration

  catalog.api:
    image: eshopai/catalog.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
      args:
        - configuration
    depends_on:
      - sql.data
      - nosql.data
      - rabbitmq

  identity.api:
    image: eshopai/identity.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile    
      args:
        - configuration
    depends_on:
      - sql.data

  ordering.api:
    image: eshopai/ordering.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile    
      args:
        - configuration
    depends_on:
      - sql.data
      - rabbitmq

  ordering.backgroundtasks:
    image: eshop/ordering.backgroundtasks:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.BackgroundTasks/Dockerfile    
      args:
        - configuration
    depends_on:
      - sql.data
      - rabbitmq

  marketing.api:
    image: eshopai/marketing.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Marketing/Marketing.API/Dockerfile    
    depends_on:
      - sql.data
      - nosql.data
      - identity.api
      - rabbitmq

  webmvc:
    image: eshopai/webmvc:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebMVC/Dockerfile    
      args:
        - configuration
    depends_on:
      - catalog.api
      - ordering.api
      - identity.api
      - basket.api
      - marketing.api
      - ai.productrecommender.azureml.api
      - ai.productsearchimagebased.tensorflow.api
      - ai.productsearchimagebased.azurecognitiveservices.api
      - ordering.backgroundtasks
      - ordering.signalrhub
      - webshoppingagg
      - webshoppingapigw
      - webaiapigw

  webraz:
    image: eshopai/webraz:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebDashboardRazor/Dockerfile    
      args:
        - configuration
    depends_on:
      - catalog.api
      - ordering.api
      - identity.api
      - ai.salesforecasting.mlnet.api
      - webshoppingapigw
      - webaiapigw

  webstatus:
    image: eshopai/webstatus:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebStatus/Dockerfile

  payment.api:
    image: eshopai/payment.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Payment/Payment.API/Dockerfile
    depends_on:
      - rabbitmq    
    
  locations.api:
    image: eshopai/locations.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Location/Locations.API/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    volumes:
      - ./mssql:/var/opt/bulk

  nosql.data:
    image: mongo

  basket.data:
    image: redis:alpine
      
  rabbitmq:
    image: rabbitmq:3-management-alpine

  mobileshoppingapigw:
    image: eshopai/ocelotapigw:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
 
  mobilemarketingapigw:
    image: eshopai/ocelotapigw:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
 
  webshoppingapigw:
    image: eshopai/ocelotapigw:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile

  webmarketingapigw:
    image: eshopai/ocelotapigw:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile

  mobileshoppingagg:
    image: eshopai/mobileshoppingagg:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/Mobile.Bff.Shopping/aggregator/Dockerfile

  webshoppingagg:
    image: eshopai/webshoppingagg:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/Web.Bff.Shopping/aggregator/Dockerfile

  webaiapigw:
    image: eshopai/ocelotapigw:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile

  ordering.signalrhub:
    image: eshop/ordering.signalrhub:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.SignalrHub/Dockerfile
      args:
        - configuration

