version: '3.3'

services:

  basket.api:
    image: eshopai/basket.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile    
    depends_on:
      - basket.data
      - identity.api
      - rabbitmq

  ai.productrecommender.azureml.api:
    image: eshopai/ai.productrecommender.azureml.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/AI.ProductRecommender/AI.ProductRecommender.AzureML.API/Dockerfile    

  ai.productsearchimagebased.tensorflow.api:
    image: eshopai/ai.productsearchimagebased.tensorflow.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/AI.ProductSearchImageBased/AI.ProductSearchImageBased.TensorFlow.API/Dockerfile    

  ai.productsearchimagebased.azurecognitiveservices.api:
    image: eshopai/ai.productsearchimagebased.azurecognitiveservices.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/AI.ProductSearchImageBased/AI.ProductSearchImageBased.AzureCognitiveServices.API/Dockerfile    

  catalog.api:
    image: eshopai/catalog.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - sql.data
      - nosql.data
      - rabbitmq

  identity.api:
    image: eshopai/identity.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile    
    depends_on:
      - sql.data

  ordering.api:
    image: eshopai/ordering.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq

  ordering.backgroundtasks:
    image: eshop/ordering.backgroundtasks:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.BackgroundTasks/Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq

  marketing.api:
    image: eshopai/marketing.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Marketing/Marketing.API/Dockerfile    
    depends_on:
      - sql.data
      - nosql.data
      - identity.api
      - rabbitmq

  webmvc:
    image: eshopai/webmvc:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebMVC/Dockerfile    
    depends_on:
      - catalog.api
      - ordering.api
      - identity.api
      - basket.api
      - marketing.api
      - ai.productrecommender.azureml.api
      - ai.productsearchimagebased.tensorflow.api
      - ai.productsearchimagebased.azurecognitiveservices.api

  webstatus:
    image: eshopai/webstatus:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebStatus/Dockerfile

  payment.api:
    image: eshopai/payment.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Payment/Payment.API/Dockerfile
    depends_on:
      - rabbitmq    
    
  locations.api:
    image: eshopai/locations.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Location/Locations.API/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    volumes:
      - ./mssql:/var/opt/bulk

  nosql.data:
    image: mongo

  basket.data:
    image: redis:alpine
      
  rabbitmq:
    image: rabbitmq:3-management-alpine